### ISSUE TITLE
text file of splits

### ISSUE THREAD

**Issue by pj771** [omni-us/research-WriterAdaptation-HTR#1]
Hi,

congrats on your great work.

I was wondering if it would be possible to release the text file for iam dataset splits. Specifically looking for text files 'RWTH.iam_word_gt_final.valid.thresh' and 'RWTH.iam_word_gt_final.test.thresh'.

Thanks

**Comment by leitro** [comment]
Hi! Yes, please refer to [our previous repo](https://github.com/omni-us/research-seq2seq-HTR/tree/master/RWTH_partition) to find the partition files. Cheers!

**Comment by pj771** [comment]
thanks
